#!/usr/bin/env python3
"""Export stories260K for the C model: int8 weights, calibrated static output scales, a C header.

Writes llm/weights/stories260k.h, then reads the header back and runs the Lean GEMM contract from
the parsed values only. The greedy tokens must match stories_int8.py in lean mode, so a mistake in
the export shows up here and not on the FPGA.

  python export_stories.py

Weights are stored as TensorI8 expects them (llm/include/llm.h): row-major [K, N] for
C[M, N] = A[M, K] * B[K, N], i.e. transposed from llama2.c's [out, in]. One scale per tensor.
The token embedding stays float: it is a table lookup on the CPU, not a GEMM.
"""

import re
import sys
from pathlib import Path

import numpy as np

from stories_int8 import CALIB_PROMPTS, Gemm, calibrate, generate, load, q8

OUT = Path(__file__).resolve().parent.parent / "weights" / "stories260k.h"
PROMPT = "Once upon a time"
N_NEW = 30

# (header name, GEMM name in stories_int8.forward, weights per layer)
LAYER_W = [("wq", "q", "wq"), ("wk", "k", "wk"), ("wv", "v", "wv"), ("wo", "o", "wo"),
           ("w1", "w1", "w1"), ("w3", "w3", "w3"), ("w2", "w2", "w2")]
ACT_GEMMS = ["qk", "av"]    # attention: both operands are activations, only the output scale is static


def c_array(ctype, name, values, per_line=32):
    vals = [f"{v:.9g}" if ctype == "float" else str(int(v)) for v in np.ravel(values)]
    lines = [", ".join(vals[i:i + per_line]) for i in range(0, len(vals), per_line)]
    return f"static const {ctype} {name}[{len(vals)}] = {{\n  " + ",\n  ".join(lines) + "\n};\n"


def export(m, scales, prompt, expected):
    L = m.n_layers
    h = [f"/* Generated by llm/tools/export_stories.py from stories260K (karpathy/tinyllamas, MIT). Do not edit.\n"
         f"   Weights: int8, one scale per tensor, row-major [K, N]. Output scales: one static scale per GEMM,\n"
         f"   calibrated on {len(CALIB_PROMPTS)} prompts, for Gemmini's int8 read-out (Lean config). */\n",
         "#ifndef STORIES260K_H\n#define STORIES260K_H\n\n#include <stdint.h>\n\n",
         "enum {\n"
         f"  ST_DIM = {m.dim},\n  ST_HIDDEN = {m.hidden},\n  ST_LAYERS = {L},\n  ST_HEADS = {m.n_heads},\n"
         f"  ST_KV_HEADS = {m.n_kv},\n  ST_HEAD_DIM = {m.head},\n  ST_VOCAB = {m.vocab},\n  ST_MAX_SEQ = {m.seq_len},\n"
         f"  ST_PROMPT_LEN = {len(prompt)},\n  ST_EXPECTED_LEN = {len(expected)}\n}};\n\n"]
    h.append(f"/* {PROMPT!r} as token ids (BOS first), and the greedy continuation in lean mode. */\n")
    h.append(c_array("int", "st_prompt", prompt))
    h.append(c_array("int", "st_expected", expected))
    h.append("\n")
    h.append(c_array("float", "st_tok_emb", m.tok_emb))
    h.append(c_array("float", "st_rms_att", m.rms_att))
    h.append(c_array("float", "st_rms_ffn", m.rms_ffn))
    h.append(c_array("float", "st_rms_final", m.rms_final))
    for hname, gname, attr in LAYER_W:
        qs, ss = [], []
        for l in range(L):
            q, s = q8(getattr(m, attr)[l])
            qs.append(q.T)
            ss.append(s)
        h.append(c_array("int8_t", f"st_{hname}", qs))
        h.append(c_array("float", f"st_{hname}_scale", ss))
        h.append(c_array("float", f"st_{hname}_out_scale", [scales[f"L{l}.{gname}"] for l in range(L)]))
    for gname in ACT_GEMMS:
        h.append(c_array("float", f"st_{gname}_out_scale", [scales[f"L{l}.{gname}"] for l in range(L)]))
    q, s = q8(m.wcls)
    h.append(c_array("int8_t", "st_wcls", q.T))
    h.append(c_array("float", "st_wcls_scale", [s]))
    h.append(c_array("float", "st_wcls_out_scale", [scales["lm_head"]]))
    h.append("\n#endif\n")
    OUT.write_text("".join(h))


def parse(path):
    """Every array in the header, by name."""
    text = path.read_text()
    arrays = {}
    for ctype, name, n, body in re.findall(r"static const (\w+) (\w+)\[(\d+)\] = \{(.*?)\};", text, re.S):
        a = np.array([float(x) for x in body.replace("\n", " ").split(",")])
        assert a.size == int(n), name
        arrays[name] = a.astype(np.int64) if ctype in ("int8_t", "int") else a
    return arrays


class HeaderGemm(Gemm):
    """Lean contract with the int8 weights and all scales taken from the parsed header."""

    def __init__(self, arr, m):
        L = m.n_layers
        scales = {"lm_head": arr["st_wcls_out_scale"][0]}
        for hname, gname, attr in LAYER_W:
            for l in range(L):
                scales[f"L{l}.{gname}"] = arr[f"st_{hname}_out_scale"][l]
        for gname in ACT_GEMMS:
            for l in range(L):
                scales[f"L{l}.{gname}"] = arr[f"st_{gname}_out_scale"][l]
        super().__init__("lean", scales)
        self.w = {}
        for hname, gname, attr in LAYER_W:
            k, n = getattr(m, attr).shape[2], getattr(m, attr).shape[1]
            per = arr[f"st_{hname}"].reshape(L, k, n)
            for l in range(L):
                self.w[f"L{l}.{gname}"] = (per[l].T, arr[f"st_{hname}_scale"][l])   # back to [out, in]
        self.w["lm_head"] = (arr["st_wcls"].reshape(m.dim, m.vocab).T, arr["st_wcls_scale"][0])

    def __call__(self, name, a, b, b_is_weight):
        if not b_is_weight:
            return super().__call__(name, a, b, b_is_weight)
        aq, a_s = q8(a)
        bq, b_s = self.w[name]
        acc = aq @ bq.T
        s_o = self.out_scales[name]
        return np.clip(np.rint(acc * (a_s * b_s / s_o)), -128, 127) * s_o


def main():
    m, tok = load()
    scales = calibrate(m, tok)
    prompt = tok.encode(PROMPT)
    expected = generate(m, Gemm("lean", scales), prompt, N_NEW)[len(prompt):]
    export(m, scales, prompt, expected)
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KiB), {len(scales)} output scales")

    arr = parse(OUT)
    for name, ref in [("st_tok_emb", m.tok_emb), ("st_rms_att", m.rms_att), ("st_rms_ffn", m.rms_ffn),
                      ("st_rms_final", m.rms_final)]:
        assert np.array_equal(arr[name].astype(np.float32), np.ravel(ref)), name
    got = generate(m, HeaderGemm(arr, m), list(arr["st_prompt"]), N_NEW)[len(prompt):]
    print(f"prompt   {PROMPT!r} -> {prompt}")
    print(f"expected {tok.decode(prompt[1:] + expected)!r}")
    if got != expected:
        print(f"header   {tok.decode(prompt[1:] + got)!r}\nMISMATCH: the header does not reproduce lean mode")
        sys.exit(1)
    print("header round trip: same greedy tokens as lean mode")


if __name__ == "__main__":
    main()
